# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/dtn-neighbor-msg/dtn-neighbor-msg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/dtn-neighbor-msg/dtn-neighbor-msg/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/runner/work/dtn-neighbor-msg/dtn-neighbor-msg/build && $(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/dtn-neighbor-msg/dtn-neighbor-msg/build/CMakeFiles /home/runner/work/dtn-neighbor-msg/dtn-neighbor-msg/build/spec//CMakeFiles/progress.marks
	cd /home/runner/work/dtn-neighbor-msg/dtn-neighbor-msg/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spec/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/dtn-neighbor-msg/dtn-neighbor-msg/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/runner/work/dtn-neighbor-msg/dtn-neighbor-msg/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spec/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/runner/work/dtn-neighbor-msg/dtn-neighbor-msg/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spec/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/runner/work/dtn-neighbor-msg/dtn-neighbor-msg/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spec/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/runner/work/dtn-neighbor-msg/dtn-neighbor-msg/build && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
spec/CMakeFiles/specs.dir/rule:
	cd /home/runner/work/dtn-neighbor-msg/dtn-neighbor-msg/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spec/CMakeFiles/specs.dir/rule
.PHONY : spec/CMakeFiles/specs.dir/rule

# Convenience name for target.
specs: spec/CMakeFiles/specs.dir/rule

.PHONY : specs

# fast build rule for target.
specs/fast:
	cd /home/runner/work/dtn-neighbor-msg/dtn-neighbor-msg/build && $(MAKE) $(MAKESILENT) -f spec/CMakeFiles/specs.dir/build.make spec/CMakeFiles/specs.dir/build
.PHONY : specs/fast

# Convenience name for target.
spec/CMakeFiles/cborerrors.dir/rule:
	cd /home/runner/work/dtn-neighbor-msg/dtn-neighbor-msg/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spec/CMakeFiles/cborerrors.dir/rule
.PHONY : spec/CMakeFiles/cborerrors.dir/rule

# Convenience name for target.
cborerrors: spec/CMakeFiles/cborerrors.dir/rule

.PHONY : cborerrors

# fast build rule for target.
cborerrors/fast:
	cd /home/runner/work/dtn-neighbor-msg/dtn-neighbor-msg/build && $(MAKE) $(MAKESILENT) -f spec/CMakeFiles/cborerrors.dir/build.make spec/CMakeFiles/cborerrors.dir/build
.PHONY : cborerrors/fast

# Convenience name for target.
spec/CMakeFiles/cddlerrors.dir/rule:
	cd /home/runner/work/dtn-neighbor-msg/dtn-neighbor-msg/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spec/CMakeFiles/cddlerrors.dir/rule
.PHONY : spec/CMakeFiles/cddlerrors.dir/rule

# Convenience name for target.
cddlerrors: spec/CMakeFiles/cddlerrors.dir/rule

.PHONY : cddlerrors

# fast build rule for target.
cddlerrors/fast:
	cd /home/runner/work/dtn-neighbor-msg/dtn-neighbor-msg/build && $(MAKE) $(MAKESILENT) -f spec/CMakeFiles/cddlerrors.dir/build.make spec/CMakeFiles/cddlerrors.dir/build
.PHONY : cddlerrors/fast

# Convenience name for target.
spec/CMakeFiles/cborvalid.dir/rule:
	cd /home/runner/work/dtn-neighbor-msg/dtn-neighbor-msg/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spec/CMakeFiles/cborvalid.dir/rule
.PHONY : spec/CMakeFiles/cborvalid.dir/rule

# Convenience name for target.
cborvalid: spec/CMakeFiles/cborvalid.dir/rule

.PHONY : cborvalid

# fast build rule for target.
cborvalid/fast:
	cd /home/runner/work/dtn-neighbor-msg/dtn-neighbor-msg/build && $(MAKE) $(MAKESILENT) -f spec/CMakeFiles/cborvalid.dir/build.make spec/CMakeFiles/cborvalid.dir/build
.PHONY : cborvalid/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cborerrors"
	@echo "... cborvalid"
	@echo "... cddlerrors"
	@echo "... specs"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/runner/work/dtn-neighbor-msg/dtn-neighbor-msg/build && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

